// App-shell niceties: offline service worker (dist build only) and iOS gesture guards.

/**
 * Register the service worker generated by the build (see vite.config.ts). Never in dev (no worker
 * exists there, and caching would fight HMR) and never in the single-file build (it has no files to
 * cache and may be opened from file://).
 */
export function registerServiceWorker(): void {
  if (!import.meta.env.PROD || import.meta.env.MODE === 'single') return;
  if (!('serviceWorker' in navigator) || !/^https?:$/.test(location.protocol)) return;
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('./sw.js').catch(() => {
      /* offline support is a bonus */
    });
  });
}

/** Stop the page itself from zooming, rubber-banding or selecting while people draw. */
export function installTouchGuards(): void {
  const opts = { passive: false } as AddEventListenerOptions;
  // Pinch-zoom (iOS Safari ignores user-scalable=no).
  document.addEventListener('gesturestart', (e) => e.preventDefault(), opts);
  document.addEventListener('gesturechange', (e) => e.preventDefault(), opts);
  document.addEventListener('dblclick', (e) => e.preventDefault(), opts);
  // Rubber-band / pull-to-refresh: nothing in the app scrolls natively, so no touchmove needs the default.
  document.addEventListener(
    'touchmove',
    (e) => {
      if ((e.target as HTMLElement | null)?.closest?.('input[type=range]')) return;
      e.preventDefault();
    },
    opts,
  );
  // Double-tap zoom on iOS: swallow a second touchend that lands quickly on the same spot.
  let lastEnd = 0;
  document.addEventListener(
    'touchend',
    (e) => {
      const now = e.timeStamp;
      const t = e.target as HTMLElement | null;
      if (now - lastEnd < 320 && !t?.closest?.('button, input, [role=button]')) e.preventDefault();
      lastEnd = now;
    },
    opts,
  );
  document.addEventListener('contextmenu', (e) => {
    if (!(e.target as HTMLElement | null)?.closest?.('input')) e.preventDefault();
  });
}
